<?php

namespace Plugin\SliderPlugin4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\SliderPlugin4\Entity\SilderCategoryImage;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * SilderCategoryImageRepository.
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SilderCategoryImageRepository extends AbstractRepository
{
    /**
     * SilderCategoryImageRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, SilderCategoryImage::class);
    }
}
